monitoring_namespace: "monitoring"
monitoring_helm: "monitoring"

monitoring_prom_datasource_name: "Prometheus"
monitoring_prom_datasource_type: "prometheus"
monitoring_prom_datasource_url: "http://monitoring-kube-prometheus-prometheus.monitoring:9090/"
monitoring_prom_datasource_uid: "prometheus"

monitoring_loki_datasource_name: "Loki"
monitoring_loki_datasource_type: "loki"
monitoring_loki_datasource_url: "http://loki.logs.svc.cluster.local:3100"
monitoring_loki_datasource_uid: "loki"

monitoring_values:
  grafana:
    enabled: true
    adminPassword: admin
    service:
      enabled: true
      type: NodePort
      nodePort: 30000
    defaultDashboardsEnabled: false
    sidecar:
      datasources:
        defaultDatasourceEnabled: false
    datasources:
      datasources.yaml:
        apiVersion: 1
        datasources:
        - name: "{{ monitoring_prom_datasource_name }}"
          type: "{{ monitoring_prom_datasource_type }}"
          url: "{{ monitoring_prom_datasource_url }}"
          uid: "{{ monitoring_prom_datasource_uid }}"
          access: proxy
          isDefault: true
        - name: "{{ monitoring_loki_datasource_name }}"
          type: "{{ monitoring_loki_datasource_type }}"
          url: "{{ monitoring_loki_datasource_url }}"
          uid: "{{ monitoring_loki_datasource_uid }}"
          access: proxy
          isDefault: false
          jsonData:
            maxLines: 1000
            httpHeaderName1: 'X-Scope-OrgID'
          secureJsonData:
            httpHeaderValue1: 'default'
    dashboardProviders:
      dashboardproviders.yaml:
        apiVersion: 1
        providers:
        - name: 'default'
          orgId: 1
          folder: ''
          type: file
          disableDeletion: false
          editable: true
          options:
            path: /var/lib/grafana/dashboards/default
    dashboards:
      default:
        kube-state:
          gnetId: 13332
          revision: 12
          datasource: Prometheus
        cluster-overview:
          gnetId: 7249
          revision: 1
          datasource: Prometheus
        volumes:
          gnetId: 11454
          revision: 14
          datasource: Prometheus
        trivy-operator:
          gnetId: 17813
          revision: 2
          datasource: Prometheus
        custom-dashboard:
          json: |
            {{ lookup('file', role_path + '/files/dashboards/node-exporter.json') | indent(12, true) }}
  alertmanager:
    enabled: true
    config:
      global:
        resolve_timeout: 5m
        smtp_smarthost: "{{ smtp_smarthost }}" # Адрес SMTP-сервера
        smtp_from: "{{ smtp_from }}" # Адрес, который будет указан в поле "От кого"
        smtp_auth_username: "{{ smtp_auth_username }}" # Логин — это полный адрес вашего нового технического ящика
        smtp_auth_password: "{{ smtp_auth_password }}" # Пароль — сгенерированный App Password!
        smtp_require_tls: true
      route:
        group_by: ['alertname', 'namespace', 'severity']  # Группировка
        group_wait: 30s           # Время ожидания перед отправкой первой группы
        group_interval: 5m        # Интервал между отправками новых алертов в группу
        repeat_interval: 4h       # Как часто повторять, если алерт не resolved
        receiver: 'email-notifications'
        routes:
        - receiver: 'null'
          matchers:
            - alertname = "Watchdog"
      receivers:
        - name: 'null'
        - name: 'email-notifications'
          email_configs:
            - to: "{{ smtp_to }}" #Кому отправлять
              send_resolved: true
