{
 "title": "Falco logs",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "auto",
 "templating": {
  "list": [
   {
    "name": "namespace",
    "label": "namespace",
    "query": {}
   },
   { "name": "datasource", "label": "datasource", "query": "loki" },
   {
    "name": "priority",
    "label": "priority",
    "query": {}
   },
   { "name": "line_filter", "label": "line_filter" }
  ]
 },
 "panels": [
  {
   "title": "Priority counts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(priority) (rate({priority=~\".+\"} | logfmt | k8s_ns_name =~ `$namespace` | priority =~ `$priority` [$__auto]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Rules counts",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "sum" ] } },
   "targets": [
    {
     "expr": "count by(rule) (rate({priority=~\".+\", rule!=\"Falco internal: metrics snapshot\"} | logfmt | k8s_ns_name =~ `$namespace` | priority =~ `$priority` [$__auto]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by(k8s_pod_name, rule, priority, k8s_ns_name) (rate({priority=~\".+\"} | logfmt | k8s_ns_name =~ `$namespace` | priority =~ `$priority` [$__auto]))"
    }
   ]
  },
  {
   "title": "Realtime logs",
   "type": "logs",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
   "targets": [
    {
     "direction": "backward",
     "expr": "{priority=~\".+\"} |= `$line_filter` | logfmt | k8s_ns_name =~ `$namespace` | priority =~ `$priority`"
    }
   ]
  },
  {
   "title": "Priorities Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(priority) (rate({priority=~\".+\"} | logfmt | k8s_ns_name =~ `$namespace` | priority =~ `$priority` [1m]))",
     "legendFormat": "{{priority}}"
    }
   ]
  },
  {
   "title": "Rules Rates",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count by(rule) (rate({priority=~\".+\"} | logfmt | k8s_ns_name =~ `$namespace` | priority =~ `$priority` [1m]))",
     "legendFormat": "{{priority}}"
    }
   ]
  }
 ]
}