- name: Products | Install falco
  kubernetes.core.helm:
    name: "{{ falco_helm }}"
    chart_ref: falcosecurity/falco
    chart_version: "8.0.1"
    release_namespace: "{{ falco_namespace }}"
    values: "{{ falco_values }}"
    wait: true
    wait_timeout: "360s"
  when: falco_enabled

- name: Products | Install Trivy-Operator
  kubernetes.core.helm:
    name: "{{ trivy_operator_helm }}"
    chart_ref: aqua/trivy-operator
    chart_version: "0.32.1"
    release_namespace: "{{ trivy_operator_namespace }}"
    values: "{{ trivy_operator_values }}"
    wait: true
    wait_timeout: "360s"
  when: trivy_operator_enabled