[local]
localhost ansible_connection=local

[local:vars]
project_root="{{ lookup('env', 'VENV_PATH') }}"
ansible_python_interpreter="{{ project_root }}/bin/python3"
#KUBECONFIG="{{ lookup('env', 'KUBECONFIG') }}"
node_ip="{{ lookup('env', 'NODE_IP') }}"
