- name: Remove | Uninstall Helm releases
  kubernetes.core.helm:
    name: "{{ item.name }}"
    namespace: "{{ item.namespace }}"
    state: absent
    wait: true
  loop: "{{ remove_helm_releases }}"

- name: Remove | Delete namespaces
  kubernetes.core.k8s:
    api_version: v1
    kind: Namespace
    name: "{{ item }}"
    state: absent
  loop: "{{ remove_namespaces }}"

- name: Remove | Delete monitoring CRDs
  kubernetes.core.k8s:
    kind: CustomResourceDefinition
    name: "{{ item }}"
    state: absent
  loop: "{{ remove_crd_monitoring_items }}"

- name: Remove | Delete Trivy operator CRDs
  kubernetes.core.k8s:
    kind: CustomResourceDefinition
    name: "{{ item }}"
    state: absent
  loop: "{{ remove_crd_trivy_operators_items }}"

- name: Remove | Success message
  ansible.builtin.debug:
    msg: "Удаление завершено успешно! Все Helm-релизы, namespaces и CRDs удалены."
